if(!chargen_gear)
	var chargen_gear = Array();

chargen_gear = chargen_gear.concat( Array(
	/* Mundane Items */
	{
		name: "Backpack",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 1,
		weight: 2,
		cost: 50,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Bedroll (sleeping bag; winterized)",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 4,
		cost: 25,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Blanket",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 4,
		cost: 10,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Camera (disposable)",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 1,
		cost: 10,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Camera (regular)",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 2,
		cost: 75,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Camera (digital)",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 1,
		cost: 300,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Candle (provides light in 2\" radius)",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: .5,
		cost: 1,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Canteen (waterskin)",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 1,
		cost: 5,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Cellular Phone",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 0,
		cost: 100,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Crowbar",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 2,
		cost: 10,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Flashlight (10\" beam)",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 3,
		cost: 20,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Flask (ceramic)",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 1,
		cost: 5,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Flint and Steel",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 1,
		cost: 3,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Grappling Hook",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 2,
		cost: 100,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Hammer",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 1,
		cost: 10,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Lantern (provides light in 4” radius)",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 3,
		cost: 25,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Lighter",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 0,
		cost: 2,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Lockpicks",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 1,
		cost: 200,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Handcuffs (Manacles)",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 2,
		cost: 15,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Oil (for lantern; 1 pint)",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 1,
		cost: 2,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Quiver (holds 20 arrows/bolts)",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 1,
		weight: 2,
		cost: 25,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Rope (10\")",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 10,
		cost: 15,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Shovel",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 5,
		cost: 5,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Soap",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: .2,
		cost: 1,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Tool Kit",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 5,
		cost: 200,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Torch (1 hour, 4” radius)",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 1,
		cost: 5,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Umbrella",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 2,
		cost: 5,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Whistle",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 0,
		cost: 2,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Whetstone",
		class: "Adventuring Gear",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 1,
		cost: 5,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Camouflage Fatigues",
		class: "Clothing",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 0,
		cost: 20,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Hiking Boots",
		class: "Clothing",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 0,
		cost: 100,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Normal Clothing",
		class: "Clothing",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 0,
		cost: 20,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Formal Clothing",
		class: "Clothing",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 0,
		cost: 200,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Winter Gear",
		class: "Clothing",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 3,
		cost: 200,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Winter Boots",
		class: "Clothing",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 1,
		cost: 100,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Fast Food Meal (cheap meal)",
		class: "Food",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 1,
		cost: 5,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Good Meal (restaurant)",
		class: "Food",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 1,
		cost: "15+",
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "MRE (Meal Ready to Eat)",
		class: "Food",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 1,
		cost: 10,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Trail Rations (5 meals; keeps 1 week)",
		class: "Food",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 5,
		cost: 10,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Horse",
		class: "Animals & Tack",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 0,
		cost: 300,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "War Horse",
		class: "Animals & Tack",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 0,
		cost: 750,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Saddle",
		class: "Animals & Tack",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 10,
		cost: 10,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Elaborate Saddle",
		class: "Animals & Tack",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 10,
		cost: 50,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "War Horse Barding (+3)",
		class: "Animals & Tack",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 30,
		cost: 1250,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Desktop Computer",
		class: "Computers",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 20,
		cost: 800,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Laptop Computer",
		class: "Computers",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 5,
		cost: 1200,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Handheld Computer",
		class: "Computers",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 1,
		cost: 250,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "GPS",
		class: "Computers",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 1,
		cost: 250,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Cellular Interceptor",
		class: "Surveillance",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 5,
		cost: 650,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Lineman’s Telephone",
		class: "Surveillance",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 2,
		cost: 150,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Active Night Vision Goggles",
		class: "Surveillance",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 4,
		cost: 2500,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Passive Night Vision Goggles",
		class: "Surveillance",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 3,
		cost: 1000,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Parabolic Microphone",
		class: "Surveillance",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 4,
		cost: 750,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Telephone Tap",
		class: "Surveillance",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 0,
		cost: 250,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Transmitter Detector",
		class: "Surveillance",
		general: "Mundane Items",
		type: "",
		container: 0,
		weight: 1,
		cost: 525,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Arrow (normal)",
		class: "",
		general: "Ammunition",
		type: "",
		weight: .2,
		cost: .5,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Arrow (man-killer)",
		class: "",
		general: "Ammunition",
		type: "",
		weight: .2,
		cost: 1,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Arrow (teflon)",
		class: "",
		general: "Ammunition",
		type: "",
		weight: .2,
		cost: 5,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Bullets, Small",
		class: "",
		general: "Ammunition",
		type: "",
		weight: 3/50,
		cost: 10/50,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Bullets, Medium",
		class: "",
		general: "Ammunition",
		type: "",
		weight: 5/50,
		cost: 25/50,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Bullets, Large",
		class: "",
		general: "Ammunition",
		type: "",
		weight: 8/50,
		cost: 50/50,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Quarrel",
		class: "",
		general: "Ammunition",
		type: "",
		weight: 1/5,
		cost: 2,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Laser Battery",
		class: "",
		general: "Ammunition",
		type: "",
		weight: 1,
		cost: 25,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Shot (w/powder)",
		class: "",
		general: "Ammunition",
		type: "",
		weight: 1/10,
		cost: 3,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	},
	{
		name: "Sling Stone",
		class: "",
		general: "Ammunition",
		type: "",
		weight: 1/10,
		cost: 1/20,
		notes: Array(),
		book: books_list[0],
		page: "p56",
	}



));