if(!chargen_gear)
	var chargen_gear = Array();

chargen_gear = chargen_gear.concat( Array(
	/* Hand Weapons */
	{
		name: "Dagger",
		damage: "Str+d4",
		class: "Medieval",
		general: "Hand Weapons",
		type: "Blades",
		weight: 1,
		cost: 25,
		notes: Array(),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Great Sword",
		damage: "Str+d10",
		class: "Medieval",
		general: "Hand Weapons",
		type: "Blades",
		weight: 12,
		cost: 400,
		notes: Array(
			"Parry -1",
			"2 hands"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Flail",
		damage: "Str+d6",
		class: "Medieval",
		general: "Hand Weapons",
		type: "Blades",
		weight: 8,
		cost: 200,
		notes: Array(
			"Ignores Shield Parry and Cover bonus"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Katana",
		damage: "Str+d6+2",
		class: "Medieval",
		general: "Hand Weapons",
		type: "Blades",
		weight: 6,
		cost: 1000,
		ap: 2,
		notes: Array(
			"AP 2"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Long Sword",
		damage: "Str+d8",
		class: "Medieval",
		general: "Hand Weapons",
		type: "Blades",
		weight: 8,
		cost: 300,
		ap: 0,
		notes: Array(
			"Includes Scimitars"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Rapier",
		damage: "Str+d4",
		class: "Medieval",
		general: "Hand Weapons",
		type: "Blades",
		weight: 3,
		cost: 150,
		ap: 0,
		notes: Array(
			"Parry +1"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Short Sword",
		damage: "Str+d6",
		class: "Medieval",
		general: "Hand Weapons",
		type: "Blades",
		weight: 4,
		cost: 200,
		ap: 0,
		notes: Array(
			"Includes Calvary Sabers"
		),
		book: books_list[0],
		page: "p52",
	},

	/* Axes and Mauls */
	{
		name: "Axe",
		damage: "Str+d6",
		class: "Medieval",
		general: "Hand Weapons",
		type: "Axes and Mauls",
		weight: 2,
		cost: 200,
		ap: 0,
		notes: Array(
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Battle Axe",
		damage: "Str+d8",
		class: "Medieval",
		general: "Hand Weapons",
		type: "Axes and Mauls",
		weight: 10,
		cost: 300,
		ap: 0,
		notes: Array(
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Great Axe",
		damage: "Str+d10",
		class: "Medieval",
		general: "Hand Weapons",
		type: "Axes and Mauls",
		weight: 15,
		cost: 500,
		ap: 1,
		notes: Array(
			"AP 1",
			"Parry -1",
			"2 hands"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Maul",
		damage: "Str+d8",
		class: "Medieval",
		general: "Hand Weapons",
		type: "Axes and Mauls",
		weight: 20,
		cost: 400,
		ap: 0,
		notes: Array(
			"AP 2 vs rigid armor",
			"Parry -1",
			"2 hands"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Warhammer",
		damage: "Str+d6",
		class: "Medieval",
		general: "Hand Weapons",
		type: "Axes and Mauls",
		weight: 8,
		cost: 250,
		ap: 0,
		notes: Array(
			"AP 1 vs rigid armor"
		),
		book: books_list[0],
		page: "p52",
	},
	/* Pole Arms */
	{
		name: "Halberd",
		damage: "Str+d8",
		class: "Medieval",
		general: "Hand Weapons",
		type: "Pole Arms",
		weight: 15,
		cost: 250,
		ap: 0,
		notes: Array(
			"Reach 1",
			"2 hands"
		),
		book: books_list[0],
		page: "p52",
	},

	{
		name: "Lance",
		damage: "Str+d8",
		class: "Medieval",
		general: "Hand Weapons",
		type: "Pole Arms",
		weight: 10,
		cost: 300,
		ap: 0,
		notes: Array(
			"Reach 2",
			"AP 2 when charging",
			"mounted combat only"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Pike",
		damage: "Str+d8",
		class: "Medieval",
		general: "Hand Weapons",
		type: "Pole Arms",
		weight: 25,
		cost: 400,
		ap: 0,
		notes: Array(
			"Reach 2",
			"2 hands"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Staff",
		damage: "Str+d4",
		class: "Medieval",
		general: "Hand Weapons",
		type: "Pole Arms",
		weight: 8,
		cost: 10,
		ap: 0,
		notes: Array(
			"Parry + 1",
			"Reach 1",
			"2 hands"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Spear",
		damage: "Str+d6",
		class: "Medieval",
		general: "Hand Weapons",
		type: "Pole Arms",
		weight: 5,
		cost: 100,
		ap: 0,
		notes: Array(
			"Parry + 1",
			"Reach 1",
			"2 hands"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Bangstick",
		damage: "3d6",
		class: "Modern",
		general: "Hand Weapons",
		type: "",
		weight: 2,
		cost: 5,
		ap: 0,
		notes: Array(
			"Basically a shotgun shell on a stick used in melee; must be reloaded with a fresh shell (1 action)"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Bayonet",
		damage: "Str+d4",
		class: "Modern",
		general: "Hand Weapons",
		type: "",
		weight: 1,
		cost: 25,
		ap: 0,
		notes: Array(
			"A bayonet affixed to a rifle increases the damage to Str+d6, Parry +1, Reach 1, 2 hands"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Billy Club/Baton",
		damage: "Str+d4",
		class: "Modern",
		general: "Hand Weapons",
		type: "",
		weight: 1,
		cost: 20,
		ap: 0,
		notes: Array(
			"Carried by most law-enforcement officials"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Brass Knuckles",
		damage: "Str+d4",
		class: "Modern",
		general: "Hand Weapons",
		type: "",
		weight: 1,
		cost: 10,
		ap: 0,
		notes: Array(
			"A hero wearing brass knuckles is considered to be an Unarmed Attacker"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Switchblade",
		damage: "Str+d4",
		class: "Modern",
		general: "Hand Weapons",
		type: "",
		weight: 1,
		cost: 10,
		ap: 0,
		notes: Array(
			"–2 to be Noticed if hidden"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Survival Knife",
		damage: "Str+d4",
		class: "Modern",
		general: "Hand Weapons",
		type: "",
		weight: 3,
		cost: 50,
		ap: 0,
		notes: Array(
			"Contains supplies that add +1 to Survival rolls"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Molecular Knife",
		damage: "Str+d4+2",
		class: "Futuristic",
		general: "Hand Weapons",
		type: "",
		weight: 1,
		cost: 250,
		ap: 2,
		notes: Array(
			"AP 2, Cannot be thrown"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Molecular Sword",
		damage: "Str+d8+2",
		class: "Futuristic",
		general: "Hand Weapons",
		type: "",
		weight: 8,
		cost: 500,
		ap: 4,
		notes: Array(
			"AP 4"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Laser Sword",
		damage: "Str+d6+8",
		class: "Futuristic",
		general: "Hand Weapons",
		type: "",
		weight: 5,
		cost: 1000,
		ap: 12,
		notes: Array(
			"AP 12, laser swords aren’t terribly realistic, but
are staples in many space-opera campaigns"
		),
		book: books_list[0],
		page: "p52",
	},
	{
		name: "Leather",
		class: "Medieval",
		general: "Armor",
		type: "Personal Armor",
		weight: 15,
		cost: 50,
		armor: 1,
		notes: Array(
			"Covers torso, arms, legs"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Chain Hauberk (long coat)",

		class: "Medieval",
		general: "Armor",
		type: "Personal Armor",
		weight: 25,
		cost: 300,
		armor: 2,
		notes: Array(
			"Covers torso, arms, legs"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Plate Corselet",
		class: "Medieval",
		general: "Armor",
		type: "Personal Armor",
		weight: 25,
		cost: 400,
		armor: 3,
		notes: Array(
			"Covers torso"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Plate Arms (vambrace)",
		class: "Medieval",
		general: "Armor",
		type: "Personal Armor",
		weight: 10,
		cost: 200,
		armor: 3,
		notes: Array(
			"Covers arms"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Plate Leggings (greaves)",
		class: "Medieval",
		general: "Armor",
		type: "Personal Armor",
		weight: 15,
		cost: 300,
		armor: 3,
		notes: Array(
			"Covers legs"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Pot Helm",
		class: "Medieval",
		general: "Armor",
		type: "Personal Armor",
		weight: 4,
		cost: 75,
		armor: 3,
		notes: Array(
			"50% vs. head shot"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Steel Helmet (enclosed)",
		class: "Medieval",
		general: "Armor",
		type: "Personal Armor",
		weight: 8,
		cost: 150,
		armor: 3,
		notes: Array(
			"Covers head"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Plate Barding",
		class: "Medieval",
		general: "Armor",
		type: "Barding",
		weight: 30,
		cost: 1250,
		armor: 3,
		notes: Array(
			"For horses"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Small Shield (buckler)",
		class: "Medieval",
		general: "Armor",
		type: "Shields",
		weight: 8,
		cost: 25,
		armor: 0,
		parry: 1,
		notes: Array(
			"+1 Parry"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Medium Shield",
		class: "Medieval",
		general: "Armor",
		type: "Shields",
		weight: 12,
		cost: 50,
		armor: 0,
		parry: 1,
		notes: Array(
			"+1 Parry, +2 Armor to ranged shots that hit"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Large Shield (kite, pavise)",
		class: "Medieval",
		general: "Armor",
		type: "Shields",
		weight: 20,
		cost: 200,
		armor: 0,
		parry: 2,
		notes: Array(
			"+2 Parry, +2 Armor to ranged shots that hit"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Flak Jacket",
		class: "Modern",
		general: "Armor",
		type: "Personal Armor",
		weight: 12,
		cost: 80,
		armor: "+2/+4",
		notes: Array(
			"Covers torso"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Kevlar Vest",
		class: "Modern",
		general: "Armor",
		type: "Personal Armor",
		weight: 8,
		cost: 250,
		armor: "+2/+4",
		notes: Array(
			"Covers torso only, negates 4 AP, see notes"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Kevlar Vest w/inserts",
		class: "Modern",
		general: "Armor",
		type: "Personal Armor",
		weight: 12,
		cost: 2500,
		armor: "+4/+8",
		notes: Array(
			"As Kevlar, but ceramic inserts are +8 vs. bullets"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Motorcycle Helmet",
		class: "Modern",
		general: "Armor",
		type: "Personal Armor",
		weight: 5,
		cost: 75,
		armor: 3,
		notes: Array(
			"50% chance vs. head shot"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Steel Pot (helmet)",
		class: "Modern",
		general: "Armor",
		type: "Personal Armor",
		weight: 5,
		cost: 80,
		armor: 4,
		notes: Array(
			"50% chance vs. head shot"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Infantry Battle Suit",
		class: "Future",
		general: "Armor",
		type: "Personal Armor",
		weight: 20,
		cost: "Mil",
		armor: 6,
		notes: Array(
			"Covers entire body, near-future military, bomb suit"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Hard Armor",
		class: "Future",
		general: "Armor",
		type: "Personal Armor",
		weight: 30,
		cost: "Mil",
		armor: 8,
		notes: Array(
			"Covers entire body, future military"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Powered Armor (Scout Suit)",
		class: "Future",
		general: "Armor",
		type: "Personal Armor",
		weight: 0,
		cost: "Mil",
		armor: 10,
		notes: Array(
			"Covers entire body, future military"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Powered Armor (Battle Suit)",
		class: "Future",
		general: "Armor",
		type: "Personal Armor",
		weight: 0,
		cost: "Mil",
		armor: 12,
		notes: Array(
			"Covers entire body, future military"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Powered Armor (Heavy Suit)",
		class: "Future",
		general: "Armor",
		type: "Personal Armor",
		weight: 0,
		cost: "Mil",
		armor: 14,
		notes: Array(
			"Covers entire body, future military"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Reflective Vest",
		class: "Future",
		general: "Armor",
		type: "Personal Armor",
		weight: 5,
		cost: 200,
		armor: 10,
		notes: Array(
			"Covers torso, far future, works against lasers only"
		),
		book: books_list[0],
		page: "p53",
	},
	{
		name: "Axe, Throwing",
		damage: "Str+d6",
		class: "Medieval",
		general: "Ranged Weapons",
		type: "",
		range: "3/6/12",
		weight: 2,
		cost: 75,
		notes: Array(
			""
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Bow",
		damage: "2d6",
		class: "Medieval",
		general: "Ranged Weapons",
		type: "",
		range: "12/24/48",
		weight: 2,
		min_str: 2,
		rof: 1,
		cost: 250,
		notes: Array(
			""
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Crossbow",
		damage: "2d6",
		class: "Medieval",
		general: "Ranged Weapons",
		type: "",
		range: "15/30/60",
		weight: 2,
		rof: 1,
		min_str: 2,
		ap: 2,
		cost: 250,
		notes: Array(
			"AP 2, 1 action to reload"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "English Long Bow",
		damage: "2d6",
		class: "Medieval",
		general: "Ranged Weapons",
		type: "",
		range: "15/30/60",
		weight: 5,
		rof: 1,
		min_str: 3,
		cost: 200,
		notes: Array(
			""
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Knife/Dagger",
		damage: "Str+d4",
		class: "Medieval",
		general: "Ranged Weapons",
		type: "",
		range: "3/6/12",
		weight: 1,
		cost: 25,
		notes: Array(
			""
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Sling",
		damage: "Str+d4",
		class: "Medieval",
		general: "Ranged Weapons",
		type: "",
		range: "4/8/16",
		weight: 1,
		rof: 1,
		cost: 10,
		notes: Array(
			""
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Spear",
		damage: "Str+d6",
		class: "Medieval",
		general: "Ranged Weapons",
		type: "",
		range: "3/6/12",
		weight: 5,
		rof: 1,
		min_str: 2,
		cost: 100,
		notes: Array(
			""
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Brown Bess (.75)",
		damage: "2d8",
		class: "Black Powder",
		general: "Ranged Weapons",
		type: "",
		range: "10/20/40",
		weight: 15,
		min_str: 2,
		rof: 1,
		cost: 300,
		notes: Array(
			"2 actions to reload"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Blunderbuss (8G)",
		damage: "3d6/2d6/1d6",
		class: "Black Powder",
		general: "Ranged Weapons",
		type: "",
		range: "10/20/40",
		weight: 12,
		rof: 1,
		min_str: 2,
		cost: 300,
		notes: Array(
			"2 actions to reload"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Flintlock Pistol (.60)",
		damage: "2d6+1",
		class: "Black Powder",
		general: "Ranged Weapons",
		type: "",
		range: "5/10/20",
		weight: 3,
		rof: 1,
		min_str: 0,
		cost: 150,
		notes: Array(
			"2 actions to reload"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Kentucky Rifle (.45)",
		damage: "2d8",
		class: "Black Powder",
		general: "Ranged Weapons",
		type: "",
		range: "15/30/60",
		weight: 8,
		min_str: 2,
		ap: 2,
		rof: 1,
		cost: 300,
		notes: Array(
			"3 actions to reload"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Springfield (.52)",
		damage: "2d8",
		class: "Black Powder",
		general: "Ranged Weapons",
		type: "",
		range: "15/30/60",
		weight: 11,
		min_str: 2,
		ap: 0,
		rof: 1,
		cost: 250,
		notes: Array(
			"2 actions to reload"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Derringer (.44)",
		damage: "2d6+1",
		class: "Modern",
		general: "Ranged Weapons",
		type: "Pistols",
		range: "5/10/20",
		weight: 2,
		min_str: 0,
		ap: 1,
		rof: 1,
		cost: 150,
		shots: 2,
		notes: Array(
			"AP 1"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Colt Dragoon (.44)",
		damage: "2d6+1",
		class: "Modern",
		general: "Ranged Weapons",
		type: "Pistols",
		range: "12/24/48",
		weight: 4,
		min_str: 0,
		ap: 0,
		rof: 1,
		shots: 6,
		cost: 200,
		notes: Array(
			"Revolver"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Colt 1911 (.45)",
		damage: "2d6+1",
		class: "Modern",
		general: "Ranged Weapons",
		type: "Pistols",
		range: "12/24/48",
		weight: 4,
		min_str: 0,
		ap: 1,
		rof: 1,
		shots: 7,
		cost: 200,
		notes: Array(
			"AP 1, Semi-Auto"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "S&W (.44)",
		damage: "2d6+1",
		class: "Modern",
		general: "Ranged Weapons",
		type: "Pistols",
		range: "12/24/48",
		weight: 5,
		min_str: 0,
		ap: 1,
		rof: 1,
		shots: 6,
		cost: 250,
		notes: Array(
			"AP 1, Revolver"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Desert Eagle (.50)",
		damage: "2d8",
		class: "Modern",
		general: "Ranged Weapons",
		type: "Pistols",
		range: "15/30/60",
		weight: 8,
		min_str: 0,
		ap: 1,
		rof: 1,
		shots: 7,
		cost: 300,
		notes: Array(
			"AP 2, Semi-Auto"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Desert Eagle (.50)",
		damage: "2d6",
		class: "Modern",
		general: "Ranged Weapons",
		type: "Pistols",
		range: "12/24/48",
		weight: 3,
		min_str: 0,
		ap: 1,
		rof: 1,
		shots: 17,
		cost: 200,
		notes: Array(
			"AP 1, Semi-Auto"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Peacemaker (.45)",
		damage: "2d6+1",
		class: "Modern",
		general: "Ranged Weapons",
		type: "Pistols",
		range: "12/24/48",
		weight: 3,
		min_str: 0,
		ap: 1,
		rof: 1,
		shots: 6,
		cost: 200,
		notes: Array(
			"AP 1, Revolver"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Ruger (.22)",
		damage: "2d6-1",
		class: "Modern",
		general: "Ranged Weapons",
		type: "Pistols",
		range: "10/20/40",
		weight: 2,
		min_str: 0,
		ap: 0,
		rof: 1,
		shots: 9,
		cost: 100,
		notes: Array(
			"Semi-Auto"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "S&W (.357)",
		damage: "2d6+1",
		class: "Modern",
		general: "Ranged Weapons",
		type: "Pistols",
		range: "12/24/48",
		weight: 4,
		min_str: 0,
		ap: 1,
		rof: 1,
		shots: 6,
		cost: 250,
		notes: Array(
			"AP1, Revolver"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "H&K MP5 (9mm)",
		damage: "2d6",
		class: "Modern",
		general: "Ranged Weapons",
		type: "Submachine Guns",
		range: "12/24/48",
		weight: 10,
		min_str: 0,
		ap: 1,
		rof: 3,
		shots: 30,
		cost: 300,
		notes: Array(
			"AP1, Auto"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "MP40 (9mm)",
		damage: "2d6",
		class: "Modern",
		general: "Ranged Weapons",
		type: "Submachine Guns",
		range: "12/24/48",
		weight: 11,
		min_str: 0,
		ap: 1,
		rof: 3,
		shots: 32,
		cost: 300,
		notes: Array(
			"AP1, Auto"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Tommy Gun (.45)",
		damage: "2d6+1",
		class: "Modern",
		general: "Ranged Weapons",
		type: "Submachine Guns",
		range: "12/24/48",
		weight: 13,
		min_str: 0,
		ap: 1,
		rof: 3,
		shots: 50,
		cost: 350,
		notes: Array(
			"AP1, Auto"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Uzi (9mm)",
		damage: "2d6",
		class: "Modern",
		general: "Ranged Weapons",
		type: "Submachine Guns",
		range: "12/24/48",
		weight: 9,
		min_str: 0,
		ap: 1,
		rof: 3,
		shots: 32,
		cost: 300,
		notes: Array(
			"AP1, Auto"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Double-Barrel (12g)",
		damage: "1-3d6",
		class: "Modern",
		general: "Ranged Weapons",
		type: "Shotguns",
		range: "12/24/48",
		weight: 11,
		min_str: 0,
		ap: 0,
		rof: "1-2",
		shots: 2,
		cost: 150,
		notes: Array(
			"see notes"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Pump Action (12g)",
		damage: "1-3d6",
		class: "Modern",
		general: "Ranged Weapons",
		type: "Shotguns",
		range: "12/24/48",
		weight: 8,
		min_str: 0,
		ap: 0,
		rof: 1,
		shots: 6,
		cost: 150,
		notes: Array(
			"see notes"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Sawed-Off DB (12g)",
		damage: "1-3d6",
		class: "Modern",
		general: "Ranged Weapons",
		type: "Shotguns",
		range: "5/10/20",
		weight: 6,
		min_str: 0,
		ap: 0,
		rof: "1-2",
		shots: 6,
		cost: 150,
		notes: Array(
			"see notes"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Streetsweeper (12g)",
		damage: "1-3d6",
		class: "Modern",
		general: "Ranged Weapons",
		type: "Shotguns",
		range: "12/24/48",
		weight: 10,
		min_str: 0,
		ap: 0,
		rof: 1,
		shots: 12,
		cost: 450,
		notes: Array(
			"see notes"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Barrett (.50)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Rifles",
		range: "50/100/200",
		damage: "2d10",
		rof: 1,
		cost: 750,
		weight: 35,
		shots: 11,
		min_str: 3,
		ap: 4,
		notes: Array(
			"AP 4, Snapfire, HW"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "M1 (.30)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Rifles",
		range: "24/48/96",
		damage: "2d8",
		rof: 1,
		cost: 300,
		weight: 10,
		shots: 8,
		min_str: 2,
		ap: 2,
		notes: Array(
			"AP 2, Semi-Auto"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Kar98 (7.92)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Rifles",
		range: "24/48/96",
		damage: "2d8",
		rof: 1,
		cost: 300,
		weight: 9,
		shots: 5,
		min_str: 2,
		ap: 2,
		notes: Array(
			"AP 2"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Sharps Big 50 (.50)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Rifles",
		range: "30/60/120",
		damage: "2d10",
		rof: 1,
		cost: 400,
		weight: 11,
		shots: 1,
		min_str: 3,
		ap: 2,
		notes: Array(
			"AP 2, Snapfire Penalty"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Spencer Carbine (.52)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Rifles",
		range: "20/40/80",
		damage: "2d8",
		rof: 1,
		cost: 250,
		weight: 8,
		shots: 7,
		min_str: 0,
		ap: 2,
		notes: Array(
			"AP 2"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Winchester ‘76 (.45-.47)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Rifles",
		range: "24/48/96",
		damage: "2d8",
		rof: 1,
		cost: 300,
		weight: 10,
		shots: 15,
		min_str: 2,
		ap: 2,
		notes: Array(
			"AP 2"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "AK47 (7.62)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Assault Rifles",
		range: "24/48/96",
		damage: "2d8+1",
		rof: 3,
		cost: 450,
		weight: 10,
		shots: 30,
		min_str: 2,
		ap: 2,
		notes: Array(
			"AP 2, Auto"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "H&K G3 (.308)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Assault Rifles",
		range: "24/48/96",
		damage: "2d8",
		rof: 3,
		cost: 400,
		weight: 10,
		shots: 20,
		min_str: 2,
		ap: 2,
		notes: Array(
			"AP 2, Auto"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "M-16 (5.56)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Assault Rifles",
		range: "24/48/96",
		damage: "2d8",
		rof: 3,
		cost: 400,
		weight: 8,
		shots: "20-30",
		min_str: 0,
		ap: 2,
		notes: Array(
			"AP 2, Auto, 3RB"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Steyr AUG (5.56)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Assault Rifles",
		range: "24/48/96",
		damage: "2d8",
		rof: 3,
		cost: 400,
		weight: 8,
		shots: 30,
		min_str: 0,
		ap: 2,
		notes: Array(
			"AP 2, Auto, 3RB"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Gatling (.45)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Machine Guns",
		range: "24/48/96",
		damage: "2d8",
		rof: 3,
		cost: 500,
		weight: 40,
		shots: 100,
		min_str: 2,
		ap: 2,
		notes: Array(
			"AP 2, May not move"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "M2 Browning (.50 Cal)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Machine Guns",
		range: "50/100/200",
		damage: "2d10",
		rof: 3,
		cost: 1000,
		weight: 84,
		shots: 200,
		min_str: 2,
		ap: 4,
		notes: Array(
			"AP 4, Auto, May not move, HW"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "M1919 (.30)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Machine Guns",
		range: "24/48/96",
		damage: "2d8",
		rof: 3,
		cost: 750,
		weight: 32,
		shots: 250,
		min_str: 0,
		ap: 2,
		notes: Array(
			"AP 2, May not move"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "M60 (7.62)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Machine Guns",
		range: "30/60/120",
		damage: "2d8+1",
		rof: 3,
		cost: 1000,
		weight: 33,
		shots: 250,
		min_str: 3,
		ap: 2,
		notes: Array(
			"AP 2, Snapfire"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "7.7 MG (Japanese)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Machine Guns",
		range: "30/60/120",
		damage: "2d8",
		rof: 3,
		cost: 1000,
		weight: 30,
		shots: 200,
		min_str: 0,
		ap: 2,
		notes: Array(
			"AP 2, Auto, Snapfire"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "MG34 (7.92)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Machine Guns",
		range: "30/60/120",
		damage: "2d8+1",
		rof: 3,
		cost: 500,
		weight: 26,
		shots: 200,
		min_str: 3,
		ap: 2,
		notes: Array(
			"AP 2, Snapfire"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "MG42 (7.92)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Machine Guns",
		range: "30/60/120",
		damage: "2d8+1",
		rof: 4,
		cost: 500,
		weight: 26,
		shots: 200,
		min_str: 3,
		ap: 2,
		notes: Array(
			"AP 2, Snapfire"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "SAW (5.56)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Machine Guns",
		range: "30/60/120",
		damage: "2d8",
		rof: 4,
		cost: 750,
		weight: 20,
		shots: 200,
		min_str: 3,
		ap: 2,
		notes: Array(
			"AP 2, Snapfire"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Besa MG (7.92)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Machine Guns",
		range: "40/80/160",
		damage: "2d8",
		rof: 3,
		cost: 1000,
		weight: 54,
		shots: 50,
		min_str: 0,
		ap: 2,
		notes: Array(
			"AP 2, Auto, May not move"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "DTMG (7.62)",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Machine Guns",
		range: "30/60/120",
		damage: "2d8+1",
		rof: 3,
		cost: 1000,
		weight: 26,
		shots: 60,
		min_str: 0,
		ap: 2,
		notes: Array(
			"AP 2, Auto, May not move"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "14.5mm MG",
		general: "Ranged Weapons",
		class: "Modern",
		type: "Machine Guns",
		range: "50/100/200",
		damage: "3d6",
		rof: 3,
		cost: 5000,
		weight: 30,
		shots: 100,
		min_str: 0,
		ap: 2,
		notes: Array(
			"AP 2, Auto, May not move"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Laser Pistol",
		general: "Ranged Weapons",
		class: "Futuristic",
		type: "",
		range: "15/30/60",
		damage: "1-3d6",
		rof: 1,
		cost: 200,
		weight: 4,
		shots: 24,
		min_str: 0,
		ap: 0,
		notes: Array(
			"Semi-Auto"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Laser Rifle",
		general: "Ranged Weapons",
		class: "Futuristic",
		type: "",
		range: "30/60/120",
		damage: "1-3d6",
		rof: 3,
		cost: 300,
		weight: 8,
		shots: 48,
		min_str: 0,
		ap: 0,
		notes: Array(
			"Auto, 3RB"
		),
		book: books_list[0],
		page: "p54",
	},
	{
		name: "Laser MG",
		general: "Ranged Weapons",
		class: "Futuristic",
		type: "",
		range: "50/100/200",
		damage: "1-3d6",
		rof: 5,
		cost: 500,
		weight: 15,
		shots: 200,
		min_str: 0,
		ap: 0,
		notes: Array(
			"Auto"
		),
		book: books_list[0],
		page: "p54",
	}


));